In [1]:
import pandas as pd
import numpy as np

general = pd.read_csv('data/Dados_totais.csv')
data_genre = pd.read_csv('data/data_by_genres.csv')
data_year = pd.read_csv('data/data_by_year.csv')

In [2]:
general["year"].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020],
      dtype=int64)

In [3]:
general.shape

(20311, 19)

In [4]:
general = general.drop(['explicit', 'key', 'mode'], axis=1)

In [5]:
general.isnull().sum()

valence             0
year                0
acousticness        0
artists             0
danceability        0
duration_ms         0
energy              0
id                  0
instrumentalness    0
liveness            0
loudness            0
name                0
popularity          0
speechiness         0
tempo               0
artists_song        0
dtype: int64

In [6]:
general.isna().sum()

valence             0
year                0
acousticness        0
artists             0
danceability        0
duration_ms         0
energy              0
id                  0
instrumentalness    0
liveness            0
loudness            0
name                0
popularity          0
speechiness         0
tempo               0
artists_song        0
dtype: int64

In [7]:
data_genre.head()

mode                  genres  acousticness  danceability   duration_ms   
0     1  21st century classical      0.979333      0.162883  1.602977e+05  \
1     1                   432hz      0.494780      0.299333  1.048887e+06   
2     1                   8-bit      0.762000      0.712000  1.151770e+05   
3     1                      []      0.651417      0.529093  2.328809e+05   
4     1              a cappella      0.676557      0.538961  1.906285e+05   

     energy  instrumentalness  liveness   loudness  speechiness       tempo   
0  0.071317          0.606834  0.361600 -31.514333     0.040567   75.336500  \
1  0.450678          0.477762  0.131000 -16.854000     0.076817  120.285667   
2  0.818000          0.876000  0.126000  -9.180000     0.047000  133.444000   
3  0.419146          0.205309  0.218696 -12.288965     0.107872  112.857352   
4  0.316434          0.003003  0.172254 -12.479387     0.082851  112.110362   

    valence  popularity  key  
0  0.103783   27.833333    6  
1  0.221750   52.500000    5  
2  0.975000   48.000000    7  
3  0.513604   20.859882    7  
4  0.448249   45.820071    7

In [8]:
data_genre = data_genre.drop(['key', 'mode'], axis=1)

In [9]:
data_year.head()

mode  year  acousticness  danceability    duration_ms    energy   
0     1  1921      0.886896      0.418597  260537.166667  0.231815  \
1     1  1922      0.938592      0.482042  165469.746479  0.237815   
2     1  1923      0.957247      0.577341  177942.362162  0.262406   
3     1  1924      0.940200      0.549894  191046.707627  0.344347   
4     1  1925      0.962607      0.573863  184986.924460  0.278594   

   instrumentalness  liveness   loudness  speechiness       tempo   valence   
0          0.344878  0.205710 -17.048667     0.073662  101.531493  0.379327  \
1          0.434195  0.240720 -19.275282     0.116655  100.884521  0.535549   
2          0.371733  0.227462 -14.129211     0.093949  114.010730  0.625492   
3          0.581701  0.235219 -14.231343     0.092089  120.689572  0.663725   
4          0.418297  0.237668 -14.146414     0.111918  115.521921  0.621929   

   popularity  key  
0    0.653333    2  
1    0.140845   10  
2    5.389189    0  
3    0.661017   10  
4    2.604317    5

In [10]:
data_year = data_year.drop(['key', 'mode'], axis=1)

In [11]:
data_year['year'].unique()

array([1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931,
       1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942,
       1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953,
       1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964,
       1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975,
       1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986,
       1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997,
       1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
       2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
       2020], dtype=int64)

In [12]:
data_year = data_year[data_year['year'] >= 2000]

In [13]:
data_year['year'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020],
      dtype=int64)

In [14]:
data_year.reset_index(drop=True, inplace=True)

In [15]:
import plotly.express as px

fig = px.line(data_year, x="year", y="loudness", title='Loudness over the years')
# fig.show() # Loudness over the years.png

In [ ]:
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(x=data_year['year'], y=data_year['acousticness'], name='Acousticness'))
fig.add_trace(go.Scatter(x=data_year['year'], y=data_year['valence'], name='Valence'))
fig.add_trace(go.Scatter(x=data_year['year'], y=data_year['danceability'], name='Danceability'))
fig.add_trace(go.Scatter(x=data_year['year'], y=data_year['energy'], name='Energy'))
fig.add_trace(go.Scatter(x=data_year['year'], y=data_year['liveness'], name='Liveness'))
fig.add_trace(go.Scatter(x=data_year['year'], y=data_year['speechiness'], name='Speechiness'))
fig.add_trace(go.Scatter(x=data_year['year'], y=data_year['instrumentalness'], name='Instrumentalness'))

# plot_trace.png

In [17]:
fig = px.imshow(data_year.corr(), title='Correlation between features', text_auto=True)

# fig.show() # plot_corr.png

In [18]:
data_genre['genres'].value_counts().sum()

2973

In [19]:
data_genre_1 = data_genre.drop(['genres'], axis=1)

In [20]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

SEED = 1224
np.random.seed(SEED)

pca_pipeline = Pipeline([('scaler', StandardScaler()), ('pca', PCA(n_components=2, random_state=SEED))])

In [21]:
genre_embedding_pca = pca_pipeline.fit_transform(data_genre_1)
projection = pd.DataFrame(columns=['x', 'y'], data=genre_embedding_pca)

In [22]:
projection

x         y
0     5.910268 -0.011146
1     2.787093  4.498483
2    -0.757538 -1.258495
3     1.020521 -0.931690
4     0.753911 -0.999861
...        ...       ...
2968 -0.475136 -0.017126
2969 -3.026756 -1.304983
2970 -0.832511 -1.089726
2971  1.774790 -3.695233
2972 -1.028069 -1.390709

[2973 rows x 2 columns]